### Consultar
GET http://localhost:3000/api/tasks


### crear Tarea
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "",
    "description": "",
    "poster": ""
}

### modificar tarea
PUT http://localhost:3000/api/tasks/7
Content-Type: application/json

{
    "title": "",
    "description": "",
    "poster": ""
}

### eliminar tarea
DELETE http://localhost:3000/api/tasks/2



